name: Capture Screenshots
inputs:
  folder:
    description: 'Folder to store screenshots'
    required: true
    default: 'expected'
  npm-token:
    description: 'npm token to install private packages'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 20
        registry-url: "https://npm.pkg.github.com"
        cache: "npm"
    - run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ inputs.npm-token }}
    - run: npm rebuild puppeteer
    - run: npm run build:docs:production
    - name: Create screenshots
      run: node tests/capture-screenshots.js screenshots/${{ inputs.folder }}
    - name: Upload screenshots
      uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: screenshots
